version: "3.8"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: smarthome-sql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=P@ssw0rd
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - smarthome-net

  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: dotnetweb
    ports:
      - "8880:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - smarthome-net

volumes:
  mssql_data:

networks:
  smarthome-net:
